#!/bin/bash

cd $(dirname $0)/..

CONTENT=$(uuidgen)

rm -rf dist/artifacts

mkdir -p build/${CONTENT}
mkdir -p dist/artifacts

cp -rf apply.sh build/${CONTENT}

cd build

sha1sum -b $(find ${CONTENT} -type f) > ${CONTENT}/SHA1SUMS
sha1sum ${CONTENT}/SHA1SUMS > ${CONTENT}/SHA1SUMSSUM

tar cvzf ../dist/artifacts/node-agent.tar.gz ${CONTENT}
